language: python
# python versions to use during the tests
python:
    - "3.7"
# command to install dependencies
install:
    - pip install .
# command to run tests
script:
#    - py.test --cov-report term-missing --cov=maths
#    - py.test --doctest-modules --cov=maths3 --cov-report term-missing
    - py.test
branches:
  only:
   - main
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - dcs98@pitt.edu
    on_success: always
    on_failure: always